### ISSUE TITLE
[Feature] Search users / show friends / add friend / delete friend

### ISSUE THREAD

**Issue by geoseong** [dooboolab/hackatalk-mobile#106]
## Related issue
#98 

## Notice
I opened issue in [geoseong's repository](https://github.com/geoseong/hackatalk-mobile/issues/5). so please leave any opinions and thoughts in that comments

## Branch name
`feat/usermgmt`

## Collaboration Flow
![hackatalk-mobile-collaboration](https://user-images.githubusercontent.com/19166187/75092070-98d9ad00-55b7-11ea-92b3-a4bc36e50abd.jpg)

### `users`: Search users
- branch: `feat/usermgmt/users`
- assignee: @geoseong @marktoope

### `friends`: show friends
- branch: `feat/usermgmt/friends`
- assignee: @dlgmltjr0925 @00aney

### `addFriend`: add friend
- branch: `feat/usermgmt/add-friend`
- assignee: @godon019 @haerang94

### `deleteFriend`: delete friend
- branch: `feat/usermgmt/delete-friend`
- assignee: @qkreltms

**Comment by marktoope** [comment]
hi

**Comment by dlgmltjr0925** [comment]
hi

**Comment by 00aney** [comment]
hi

**Comment by qkreltms** [comment]
Hi~

**Comment by haerang94** [comment]
hi
