### ISSUE TITLE
feat: Implement [SignUp] screen and test code

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#11]
<img width="173" alt="Screen Shot 2019-09-24 at 7 05 21 AM" src="https://user-images.githubusercontent.com/27461460/65466440-d10a8180-de99-11e9-937f-c3ac5905f20a.png">

**Comment by marsinearth** [comment]
Resolved by #52

**Comment by hyochan** [comment]
![HackaToken](https://user-images.githubusercontent.com/27461460/148633297-9b4ee8e7-b1da-46a9-a156-7f13e5b808be.png)
