### ISSUE TITLE
feat: Implement [FindPw] screen and test code

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#12]
With a ui provided in #11, build `email` `TextInput` and `send` `Button`.

**Comment by hyochan** [comment]
@marsinearth Who was the volunteer for this?

**Comment by marsinearth** [comment]
I thought that #29 is building the same compartment as what this one has to be built with, so that I thought that I glanced at my emails and @JongtaekChoi wanted to take this.

**Comment by hyochan** [comment]
@marsinearth Thanks for sharing. @JongtaekChoi Would you like me to assign you on this issue?

**Comment by hyochan** [comment]
@marsinearth Actually, I think you've miss understood. #29 is totally different.

**Comment by marsinearth** [comment]
ah, now I got it. It's actually 'revealing' the password if a certain set of given condition is fulfilled. then, I'd like to get that conditions (e.g. security questions or dob or something) and a simple design for it. Or I can  follow the same design schema as the screenshot of #11

**Comment by hyochan** [comment]
Yup you can just use thr same component you've made. Thats why I have grouped the two assignments together!

**Comment by hyochan** [comment]
FYI this screen appears when you click on "forgot password" Then users send the credential to their email.

**Comment by marsinearth** [comment]
You mean [this one](https://user-images.githubusercontent.com/27461460/67143245-684dd380-f2a4-11e9-9f10-1dba2958f7bc.png)? I'd add name as the password reveal condition only since memorizing status might be a little bit tough.

**Comment by hyochan** [comment]
@marsinearth You can follow [this](https://github.com/dooboolab/talktalk-rn/blob/master/src/components/screen/FindPw.tsx). This is exactly the same thing.

**Comment by marsinearth** [comment]
I see. I was totally confused by my experience on working on [dooboodev findPW](https://github.com/dooboolab/dooboo.dev/blob/master/src/components/screen/SignIn/index.tsx#L33-L58). This one is just a screen with a button which invoke the email send function, got it.

**Comment by marsinearth** [comment]
due to [the infrastructure of test code utils](https://github.com/dooboolab/hackatalk-mobile/pull/21/files#diff-8cc175d1af819cf71e4dba00a21d66f4), I'll postpone working on this (though it is a very light job to do)
