### ISSUE TITLE
Cannot verify my email address for sign up

### ISSUE THREAD

**Issue by mym0404** [dooboolab/hackatalk-mobile#127]
**Describe the bug**
I am adding some features in this application. I need to sign in to check my function is correctly worked. But, when I tried to sign up with an email address, then verification is failed with seems like a technical issue.

![image](https://user-images.githubusercontent.com/33388801/80781916-2389ea00-8baf-11ea-9674-835ffb54bf52.png)

![image](https://user-images.githubusercontent.com/33388801/80781795-ac545600-8bae-11ea-9464-abd7cc5094fd.png)

![image](https://user-images.githubusercontent.com/33388801/80781803-b5ddbe00-8bae-11ea-9d4f-cc0dcda4fb43.png)

```
Cannot GET /verify_email/mym0404@gmail.com/$2a$10$rqSSK7iq4Lii6ZtLDObnz.x7b7s/xpBfEhAlIj0ojEwHwcfYWxZ5C
```

**To Reproduce**

1. Sign up with email and try to verify your email address.

- OS: macOS catalina(10.15.3) with verification email 
- Browser : Chrome

**Smartphone (please complete the following information):**

- Device: iPhone 11 simulator
- OS: iOS 13.4.1

**Additional context**

`react-native info`

![image](https://user-images.githubusercontent.com/33388801/80781896-0c4afc80-8baf-11ea-8bba-2e9b9a106c49.png)

**Comment by hyochan** [comment]
@mym0404 Thanks for the issue. This might occur when the server has been updating. Would you like to try this again?

**Comment by hyochan** [comment]
Should be resolved by the time now

**Comment by mym0404** [comment]
@hyochan Yes, I can verify my email account now. Thank you 🚀
