### ISSUE TITLE
First hurdle is configuration

### ISSUE THREAD

**Issue by openmaya** [dooboolab/hackatalk-mobile#16]
**Is your feature request related to a problem? Please describe.**
When I followed up the README to run first, I need to know facebookAppId, iosClinetId, androidClientId. etc. Usually, people just want to add some features but they need to figure out where those can be found before doing it.

**Describe the solution you'd like**
All configuration change to optional. and throw exception only when the configuration is needed.

**Describe alternatives you've considered**
Plz, add docs people can understand why it is needed and where they can find it. or break down the steps when run it on iOS or Android respectively

**Additional context**
Thanks

**Comment by hyochan** [comment]
![image](https://user-images.githubusercontent.com/27461460/65770847-e28dab00-e171-11e9-886e-8bee59294814.png)

We thought we've provided that in the above readme. As you can see in many other opensource, it is very hard to make the doc taste good on everyone's point of view.

The good approach when you have this kind of problem is to share your stories with others, giving some `PR` that might be helpful to users who're going to have a similar experience. People who are moving forward will be missing lots of details that beginners might need. Those steps could be improved as new contributors get involved in our project.

**Comment by openmaya** [comment]
I read it too. I thought I need to know other background knowledge.
After removing that default value '<blablabla>' to '', fianlly I can run it.

Thanks hyochan
