### ISSUE TITLE
[Feature Request] Facebook sign in

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#26]
- [ ] Follow [the read](https://docs.expo.io/versions/latest/sdk/facebook/#__next).
- [ ] Implement feature in your own dev `env` (creating your own facebook dev account). Only erase `facebook` secret before `PR`ing.
- [ ] Write minimal test code (don't need to be perfect).
- [ ] Write `readme` on how to manage `facebook` secrets in `config.ts`.
- [ ] Write necessary variables in `config.sample.ts`.
- [ ] Write a blog (extra $10) in one of [medium dooboolab](https://medium.com/@dooboolab) or [medium react-native-seoul](https://medium.com/react-native-seoul) if you prefer Korean.

**Comment by vanayun** [comment]
Can you invite me in this Organization?
Even though I am a beginner level, I want to try the work.

**Comment by hyochan** [comment]
@vanayun We are inviting to organization only when there is contribution made by the user (even small contribution is ok). If you want to work on this `issue`, you can.

Since this is an opensource, you can work on it without any invitation :)
We always welcome new contributors!

**Comment by vanayun** [comment]
I see. I'd like to be assigned to me this work.

**Comment by hyochan** [comment]
Closed via inactivity
