### ISSUE TITLE
[Feature Request] Google sign in

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#27]
- [ ] Follow [the read](https://docs.expo.io/versions/latest/sdk/google-sign-in/#__next)
- [ ] Implement feature in your own dev `env` (creating your own google dev account). Only erase `google` secret before `PR`ing.
- [ ] Write minimal test code (don't need to be perfect).
- [ ] Write `readme` on how to manage `google` secrets in `config.ts`.
- [ ] Write necessary variables in `config.sample.ts`.
- [ ] Write a blog (extra $10) in one of [medium dooboolab](https://medium.com/@dooboolab) or [medium react-native-seoul](https://medium.com/react-native-seoul) if you prefer Korean.

**Comment by Ta2Rim** [comment]
Is there anyone who works on this feature?
Also, I wonder it's good for beginners or not.
because I'm a ReactNative beginner.

**Comment by hyochan** [comment]
It is not hard implementing but there is a burden issue in debugging (You should test this in production apk). Since there is already implemented example in [our blog](https://medium.com/react-native-seoul/react-native-프로젝트에서-expo를-이용한-googlesignin-이용기-acd0404d1977) you can just follow along.

**Comment by devohno** [comment]
If there's no assignees, can I take this?

**Comment by hyochan** [comment]
@devohno Of course you can. You can even work on it without asking! Also here is an [example](https://medium.com/react-native-seoul/react-native-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90%EC%84%9C-expo%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-googlesignin-%EC%9D%B4%EC%9A%A9%EA%B8%B0-acd0404d1977) you can follow through.

**Comment by devohno** [comment]
I got access_token on Expo client from Google api.
Getting access token, and then navigating to the [Main] screen is that all of implement of app?

**Comment by hyochan** [comment]
Currently, getting access token and showing it using `Alert` would be just fine.
