### ISSUE TITLE
[Feature Request] Build [Setting] screen which has ability to see login info and change credential

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#29]
Below is an example

[SettingAccount]
<img width="370" alt="Screen Shot 2019-10-20 at 3 15 41 PM" src="https://user-images.githubusercontent.com/27461460/67155545-81aa5a80-f34c-11e9-9197-d1fabf166f9f.png">

[ChangePasswordCurrent]
![image](https://user-images.githubusercontent.com/27461460/67155547-87a03b80-f34c-11e9-85d5-8cf03b8c62c4.png)
![image](https://user-images.githubusercontent.com/27461460/67155551-9129a380-f34c-11e9-9e0e-d5b4b146bf9c.png)

[ChangePasswordNew]
![image](https://user-images.githubusercontent.com/27461460/67155556-9dadfc00-f34c-11e9-92cc-fe7e30039c14.png)

**Comment by JongtaekChoi** [comment]
It looks fun. Can I apply for this work?

**Comment by hyochan** [comment]
@JongtaekChoi As you wish~! :tada:

**Comment by JongtaekChoi** [comment]
@hyochan Could I make missing designs and layouts necessary for this issue at my pleasure?

**Comment by hyochan** [comment]
Done #58
