### ISSUE TITLE
[Feature Request] Float [ProfileModal] on profile click

### ISSUE THREAD

**Issue by daheeahn** [dooboolab/hackatalk-mobile#33]
Hi! It's my first issue.

![Simulator Screen Shot - iPhone 11 Pro - 2019-10-24 at 10 02 26](https://user-images.githubusercontent.com/38369729/67444813-9ab15500-f645-11e9-8868-1e06ea82b314.png)

In this [Chat]  screen,
I wanna float [ProfileModal] (below) if I click 'ios-person' icon.

![스크린샷 2019-10-24 오전 10 02 41](https://user-images.githubusercontent.com/38369729/67444910-dfd58700-f645-11e9-8fd1-37ff2b4e7943.png)

**Comment by hyochan** [comment]
Nice detail~ This should definitely be in our roadmap. How do you think? Are you applicable in working on your own issue?

**Comment by daheeahn** [comment]
You mean this issue is essential to hackatalk project?
And I can do it!

**Comment by hyochan** [comment]
> You mean this issue is essential to hackatalk project?
Yes! That's what I meant.

I'll assign you on current issue 🎉
