### ISSUE TITLE
[Migration] Use [Button] from `@dooboo-ui/native`

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#34]
We'd like to implement our reusable components in [@dooboo-ui/native](https://github.com/dooboolab/dooboo-ui-native). However we are using our [Button] component seperately.

Would like to remove it and use [Button] in `@dooboo-ui/native`.

**Comment by Sandwichj** [comment]
I would like to take this issue. :)

**Comment by Sandwichj** [comment]
What format of styles would the repo [@dooboo-ui/native](https://github.com/dooboolab/dooboo-ui-native) take in the future?
[@dooboo-ui/native](https://github.com/dooboolab/dooboo-ui-native) has the both.

- camelCased by StyleSheet of [react-native](https://github.com/facebook/react-native)
![image](https://user-images.githubusercontent.com/11019960/67629304-0f3efa80-f8b7-11e9-9966-bedfee973f14.png)
- kebab-cased by [styled-components](https://github.com/styled-components/styled-components)
![image](https://user-images.githubusercontent.com/11019960/67629307-1960f900-f8b7-11e9-9c2c-d3b0fa6400ff.png)

**Comment by hyochan** [comment]
We are trying to minimize the usage of components in `@dooboo-ui/native` to increase the usability for those who are not using `styled-component`. If you have a great idea to use `styled-component` in both projects but this can also be used in other projects without it, please share.

To summarize, we are hoping `@dooboo-ui/native` works in all `react-native` projects and `hackatalk-mobile` will be `textbook` project.

**Comment by Sandwichj** [comment]
How about VSCode plugin [css-in-js](https://marketplace.visualstudio.com/items?itemName=paulmolluzzo.convert-css-in-js).
This plugin is easy to use and can support our effort to migrate from other projects which use `styled-components` to `@dooboo-ui/native` which doesn't use an additional library for css.

![image](https://user-images.githubusercontent.com/11019960/67629859-85942a80-f8c0-11e9-9af6-d0584fbf2096.png)
![image](https://user-images.githubusercontent.com/11019960/67629871-baa07d00-f8c0-11e9-959e-22f1f6634bd6.png)

**Comment by hyochan** [comment]
@Sandwichj Sorry for confusing you. Actually, we'll use `styled-component` in `@dooboo-ui/native`. I've just found this hard to re-write again when the component is bit complicating. Let's just use `styled-component` everywhere.

**Comment by Sandwichj** [comment]
@hyochan, I agree with you that using `styled-components` everywhere.
I'll refactor `@dooboo-ui/native` after resolving this issue. :)

Thanks for your opinions!

**Comment by hyochan** [comment]
@Sandwichj Would you like to remove all our buttons and replace it to button in `@dooboo-ui/native`?

**Comment by Sandwichj** [comment]
@hyochan 
Sorry for the late reply.
I'll replace all of the buttons to [@dooboo-ui/native-button](https://github.com/dooboolab/dooboo-ui-native/tree/master/src/components/shared/Button).
In progress now.

[shared/Button](https://github.com/dooboolab/hackatalk-mobile/blob/master/src/components/shared/Button.tsx) is used in:
<img src="https://user-images.githubusercontent.com/11019960/69910942-2a250180-1457-11ea-8116-0a573b5e4ee6.png" alt="Used in" width="400" /> 

Any issues that should not replace in the list?

**Comment by hyochan** [comment]
Nope. We'd like to use most `shared` components relied on `dooboo-ui/native`.
Removing current `Button` should be done.

**Comment by hyochan** [comment]
Leave it open @Sandwichj

**Comment by hyochan** [comment]
Done in #87
