### ISSUE TITLE
[Feature Request] Add agreement message and link to terms

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#37]
![image](https://user-images.githubusercontent.com/27461460/67629921-ac069580-f8c1-11e9-8add-4f483429d1c3.png)

Using [WebView](https://docs.expo.io/versions/latest/react-native/webview/) in `expo`, please do the following.

- [ ] Implement the design in `Login` screen and put below localized text at the very bottom. The design should be done in a personal sense.
   - en: We consider that you agree with `terms for agreement` and `privacy policy` by going onto next step.
   - ko: 다음 단계로 진행함과 동시에 `이용약관` 및 `개인정보취급방침`에 동의하는 것으로 간주합니다.

- [ ] should open up `webview` with [url provided](https://dooboolab.com/termsofservice) when clicking on `terms and privacy` text.
- [ ] should open up `webview` with [url provided](https://dooboolab.com/privacyandpolicy) when clicking on `privacy policy` text.

**Comment by daheeahn** [comment]
me!

**Comment by hyochan** [comment]
Closed #77
