### ISSUE TITLE
[Bug Report] small ui bug. `Send` button in [Chat] screen isn't beautiful.

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#38]
**Describe the bug**
Small ui bug. `Send` button in [Chat] screen isn't beautiful.

**Screenshots**
![image](https://user-images.githubusercontent.com/27461460/67839893-0446cd00-fb38-11e9-9750-7435b884fa94.png)

**Smartphone (please complete the following information):**

- Device: iphoneX
- OS: [e.g. iOS13]

**Comment by jbjeong-kosac** [comment]
How about this change?

<img width="436" alt="스크린샷 2019-10-30 오후 7 42 37" src="https://user-images.githubusercontent.com/55368637/67851294-7c6bbd80-fb4d-11e9-9e46-fc4023989f04.png">


It is just changing the height of Button.

height={Platform.OS === 'android' ? 40 : undefined} =>
height={40}

**Comment by jb9229** [comment]
It is fixed in the commit(https://github.com/dooboolab/hackatalk-mobile/pull/28)
Thank you.
