### ISSUE TITLE
[Feature Request] Mimic add friend & deleting friend

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#39]
Requirements
- [ ] Add friend from [SearchUser] screen.
![image](https://user-images.githubusercontent.com/27461460/67841816-3ce8a580-fb3c-11e9-9cc9-52bd2cca1afb.png)
   - Show message under `online` that friend has been added.
- [ ] Add friend in [Friend] screen.
   ![image](https://user-images.githubusercontent.com/27461460/67841955-905af380-fb3c-11e9-8692-5a3033aab372.png)
- [ ] Delete friend from [Friend] screen when clicking `Delete` in [ProfileModal] shared component.
   ![image](https://user-images.githubusercontent.com/27461460/67841981-a36dc380-fb3c-11e9-8c2d-44e78383f220.png)
- [ ] Use [immer](https://github.com/immerjs/immer)
- [ ] Test code should be provided

**Comment by dlgmltjr0925** [comment]
Me

**Comment by hyochan** [comment]
Closed #73
