### ISSUE TITLE
[Feature Request] Add more options to [GiftedChat]

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#40]
<img width="258" alt="Screen Shot 2019-10-30 at 6 02 04 PM" src="https://user-images.githubusercontent.com/27461460/67843474-63f4a680-fb3f-11e9-8612-242bf60e7d5b.png">

- [ ] Add clickable `map` icon
- [ ] Add clickable `calendar` icon
- [ ] Add clickable `file` icon
- [ ] Add clickable `sound` icon
- [ ] Add clickable `contact` icon
- [ ] Should add test cases on `onPress` interactions

**Comment by Kynyth** [comment]
`Me`

**Comment by KlausMin** [comment]
Does `sound` icon stand for `attatch audio file`?

**Comment by hyochan** [comment]
@KlausMin Yes!

**Comment by KlausMin** [comment]
I thought my work is done and I faced serveral issues about `yarn test` and `yarn lint`.

Here below is for `yarn test`
![image](https://user-images.githubusercontent.com/31463177/68546369-da838500-0418-11ea-89fb-c0a026238824.png)



And here below is for `yarn lint`
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/31463177/68546342-8a0c2780-0418-11ea-93b0-23dc4793eb7e.png">

**Comment by KlausMin** [comment]
@hyochan https://github.com/dooboolab/hackatalk-mobile/issues/40#issuecomment-552204038
Can I have some advices?

**Comment by godon019** [comment]
You are okay with `yarn test`, those warnings are okay to ignore for now.
but you have problem with `lint`. which means you haven't met proper code styles that this hackatalk project wants.
You can fix it one by one by following those error messages.
when you see this
```
30:1   errror   Expected 'multiple' syntax before 'single' syntax   sort-imports
```
this is telling you to fix your `import` statement order
you can get some ideas from [here](https://eslint.org/docs/rules/sort-imports)

and with the others 
```
error    Missing return type on function     @typescript-eslint/explicit-function-return-type
```
you can get ideas to solve those from [here](https://github.com/bradzacher/eslint-plugin-typescript/blob/master/docs/rules/explicit-function-return-type.md)

**Comment by KlausMin** [comment]
Thank you so much @godon019 !

**Comment by hyochan** [comment]
@KlausMin Can you tell us any stories?

**Comment by KlausMin** [comment]
@hyochan Sorry. My work has been very urgent so far and it's still on going. Feel free to unassign me for this issue if want to.
