### ISSUE TITLE
[Feature Request] Add [PinchZoomView] with full screen

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#41]
Add [PinchZoomView] with full screen to show image in full screen with `pinch zoom` ability.

- [ ] Design below screen
   ![image](https://user-images.githubusercontent.com/27461460/67845310-9f44a480-fb42-11e9-865f-5888b03e058c.png)
   - [ ] Image should be `pinch zoomed`.
   - [ ] Image area should be implemented in `shared` component named [PinchZoomView] or [PinchZoomHorizontalScrollView]. Imagine that this will be ported to [@dooboo-ui/native](https://github.com/dooboolab/dooboo-ui-native).
   - [ ] bonus: Image should be `carousel`. `left` `right` scroll by screen.

**Comment by hyochan** [comment]
FYI [react-native-image-zoom-viewer](https://github.com/ascoders/react-native-image-viewer)

**Comment by JeffGuKang** [comment]
Me -0-/

**Comment by JeffGuKang** [comment]
I am not sure I need to apply styled-component's theme here. What do you think?

**Comment by hyochan** [comment]
@JeffGuKang If this is `shared` component, we aren't thinking about putting theme.

**Comment by JeffGuKang** [comment]
@hyochan Okay. I will try keep the style as your example.

**Comment by hyochan** [comment]
@JeffGuKang Try to pass down the `style` props.
