### ISSUE TITLE
[Improvement] Better typing for React components

### ISSUE THREAD

**Issue by godon019** [dooboolab/hackatalk-mobile#51]
### Problem
Currently we are using `React.ReactElement` for typing a component
Which doesn't let typescript to infer `children` from its React component props
![image](https://user-images.githubusercontent.com/10363850/68376354-d0992200-018b-11ea-8e1e-1b4d2f9c00cc.png)
As we can see, we have to declare children explicitly to use it.

But if we use `React.FC` or  ~~`React.SFC`~~, typescript knows that it is React component and properly shows the `children` of React component prop
![image](https://user-images.githubusercontent.com/10363850/68376542-1950db00-018c-11ea-8960-415a50ed35eb.png)

### Solution
We can migrate it little by little

**Comment by hyochan** [comment]
Nice one 👍

**Comment by godon019** [comment]
More information! `React.SFC` is being deprecated, and they say we should use `React.FC` instead!

**Comment by hyochan** [comment]
@godon019 Could you make some update on this with your `PR` given? Since the return value is `ReactElement`, I am not quite sure when to use `React.FC`.

**Comment by godon019** [comment]
@hyochan, I am afraid but I don't know which PR you are referring to.
In general, you can always use `React.FC` instead of `ReactElement` on functional component declaration!
