### ISSUE TITLE
[Improvement] Dark Mode Automatic Recognition

### ISSUE THREAD

**Issue by real0131** [dooboolab/hackatalk-mobile#60]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Recognize the system dark mode setting and automatically activate the dark mode.

**Describe alternatives you've considered**
A method has been added to automatically recognize dark mode (from version 35 of the Expo). I am going to apply dark mode automatic recognition using the API.

**Additional context**
https://docs.expo.io/versions/latest/sdk/appearance/
https://github.com/expo/react-native-appearance

**Comment by real0131** [comment]
me

**Comment by real0131** [comment]
I want to work on it.

**Comment by hyochan** [comment]
@real0131 You are in!

**Comment by hyochan** [comment]
Merged #62
