### ISSUE TITLE
[Feature Request] Application [Settings] screen

### ISSUE THREAD

**Issue by DylanJu** [dooboolab/hackatalk-mobile#61]
**Is your feature request related to a problem? Please describe.**
In the Hackatak, there is no application settings screen. This is a common menu in other applications like Kakaotalk, Telegram, Whatsapp and so on.

**Describe the solution you'd like**
Add [Settings] screen

**Describe alternatives you've considered**
At this stage, it seems like that all menus are not needed. So, I will add just the main [Settings] screen showing dummy menu bars not working. These dummy menus will be [Notifications and Sounds] [Privacy and Security] [Language] [Announcement] 

**Additional context**

<img src="https://user-images.githubusercontent.com/17488824/69003545-78121380-0947-11ea-8278-63c1f76d333d.PNG" width="33%">
<img src="https://user-images.githubusercontent.com/17488824/69003546-78121380-0947-11ea-9500-a6fcd7ddc3a4.PNG" width="33%">
<img src="https://user-images.githubusercontent.com/17488824/69003547-78aaaa00-0947-11ea-85f4-31043fbc7738.PNG" width="33%">

**Comment by hyochan** [comment]
Thanks for the thoughtful issue 👍 , However, this looks like it's already in progress in #58. Would you like to take that `PR` and test our if it is sufficient?

**Comment by DylanJu** [comment]
OK! I will do that

**Comment by hyochan** [comment]
Closed #58
