### ISSUE TITLE
[Feature Request] Apple Authentication

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#75]
We now need to add Apple Authentication in order to add other 3rd parties social auth. 
- Follow the [doc](https://docs.expo.io/versions/latest/sdk/apple-authentication/).

**Comment by JeffGuKang** [comment]
I have been use this. -0-/

**Comment by JeffGuKang** [comment]
Sorry for late process. 
Could you set the project for apple sign in? 
We can refer [1](https://help.apple.com/developer-account/?lang=en#/devde676e696) and [2](https://help.apple.com/xcode/mac/11.0/#/dev50571b902).

And there are two Apple SignIn modules for RN. I may use [invertase/react-native-apple-authentication](https://github.com/invertase/react-native-apple-authentication). Another one is [expo-apple-authentication](https://github.com/expo/expo/tree/master/packages/expo-apple-authentication)

**Comment by hyochan** [comment]
@JeffGuKang Since we are using `expo-unimodules`, `expo-apple-authentication` should be the good choice!

**Comment by JeffGuKang** [comment]
@hyochan I got it. 👍
