### ISSUE TITLE
More apollo integrations

### ISSUE THREAD

**Issue by hyochan** [dooboolab/hackatalk-mobile#98]
Given initial works provided in #96, I'd like to share with others on apollo integrations.
Below are the tasks we can try today 🥇 .

You can see all integrated GraphqlAPIs in https://stage.hackatalk.dev/graphql

** **Currently provided** **
- [x] Add / Remove push notifications
- [x] Search all users not including user.
- [x] Add / Remove friend
- [x] Update profile
- [x] Find password
- [x] Facebook signin
- [x] Apple signin
- [x] Google signin
- [x] Change password

** **Not yet provided in server** **
- [ ] Manage on / offline users
- [x] Add channel (This can be done automatically when you've sent first message to user)
- [x] Send message (Message, Photo, File)
- [ ] Get messages with pagination
- [ ] Friend subscription
- [ ] Channel subscription
- [ ] Message subscription

** **Planed for integration** **
- [x] Auth flow (signin, me, signup, verify email)
- [ ] Social auth (apple signin, facebook signin, google signin)
   - `signInWithSocialAccount`
- [x] Find & change password / check auth type
   - `me`
   - `findPassword`
   - `changePassword`
- [x] Search users / add friends / show friends
   - `users`
   - `addFriend`
   - `friends`
   - `deleteFriend`
- [ ] Update profile
   - `updateProfile`
   - rest api : post `/upload_single` with body `inputFile`

⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️ ⭐️

Recommended steps
1. Try to test apis in https://stage.hackatalk.dev/graphql
2. Write up integration senario in medium.
    - This can be used in pull request for better understanding.
3. Write codes and integrate graphql APIs with installed apollo client.
    - [The medium blog](https://medium.com/dooboolab/integrate-apollo-client-in-react-native-app-2-738d60df727c) will tell you how to do so.
    - [Youtube tutorial](https://youtu.be/kG4Lgxdr8w4)
    - Please mind the typings.
4. Write test code.
    - This step is also in the medium and youtube.
5. Provide docs on medium and submit to `dooboolab` or `react-native-seoul`.
6. Add `enhancement` if you see anything that should be improved such as UI.

**Comment by godon019** [comment]
So we have two options to implement apollo client here
1. put apollo code inside of view component and thus remove unnecessary provider
2. put apollo code inside of provider

let's discuss of pros and cons here
if we choose 1.
pros
 - easy to customize apollo client code for view specific code
 - remove unnecessary provider codes
cons
 - removed encapsulation for side effect codes (provider)

and with 2.
pros
 - no need to change view codes
 - reuse test code
cons
 - possibly need to customize for specific functionality with same query?

please let me know how you guys think about it

**Comment by marsinearth** [comment]
> ## and with 2.
> pros
> 
> * no need to change view codes
> * reuse test code
> 
> cons
> 
> * possibly need to customize for specific functionality with same query?
> 
> please let me know how you guys think about it

I think this second one is already implemented on signUp, signIn, and verifyEmail using `useMutation` and is clearly beneficial when it comes to reusing the query

**Comment by godon019** [comment]
> > ## and with 2.
> > pros
> > 
> > * no need to change view codes
> > * reuse test code
> > 
> > cons
> > 
> > * possibly need to customize for specific functionality with same query?
> > 
> > please let me know how you guys think about it
> 
> I think this second one is already "nicely" implemented (btw, it's also AWS Amplify codeGen style, too) on signUp, signIn, and verifyEmail using `useMutation` and is clearly beneficial when it comes to reusing the query

Okay that sounds good! I would like to give it a try!

**Comment by geoseong** [comment]
@hyochan I added task called `delete friend` in `Search users / add friends / show friends` section.

User might want to delete a friend someday after the user adds some user to friend list.

please let me know if this `delete friend` task has not been intended.

**Comment by hyochan** [comment]
@geoseong You're right! I've added that for you!

**Comment by hyochan** [comment]
Closed followed by #134
